// What each of the dataset's columns means, in plain words (from the CICIoT2023 paper's feature table).
export const COLUMN_MEANING: Record<string, string> = {
  flow_duration: "How long the connection has been going, in seconds",
  Header_Length: "Total size of the packets' headers (the 'envelopes'), in bytes",
  "Protocol Type": "Which protocol, as a code: 6 = TCP, 17 = UDP, 1 = ICMP, 47 = GRE",
  Duration: "Time to live: how many network hops a packet may travel (64 is the usual value)",
  Rate: "Packets per second",
  Srate: "Packets per second going out",
  Drate: "Packets per second coming in",
  fin_flag_number: "Was the TCP 'goodbye' flag (FIN) set? 1 = yes",
  syn_flag_number: "Was the TCP 'hello, let's connect' flag (SYN) set?",
  rst_flag_number: "Was the TCP 'hang up now' flag (RST) set?",
  psh_flag_number: "Was the TCP 'deliver this right away' flag (PSH) set?",
  ack_flag_number: "Was the TCP 'got it' flag (ACK) set?",
  ece_flag_number: "Congestion warning flag (ECE)",
  cwr_flag_number: "'I slowed down' flag (CWR)",
  ack_count: "How many packets carried 'got it' (ACK), averaged over the batch",
  syn_count: "How many packets carried 'hello' (SYN), averaged over the batch",
  fin_count: "How many packets carried 'goodbye' (FIN), averaged over the batch",
  urg_count: "How many packets were marked urgent, averaged over the batch",
  rst_count: "How many packets carried 'hang up' (RST), averaged over the batch",
  HTTP: "1 if it was ordinary web traffic",
  HTTPS: "1 if it was encrypted web traffic",
  DNS: "1 if it was a 'what is this website's address?' lookup",
  Telnet: "1 if it was old-style remote login",
  SMTP: "1 if it was sending email",
  SSH: "1 if it was secure remote login",
  IRC: "1 if it was IRC chat",
  TCP: "1 if it used TCP (careful, guaranteed delivery)",
  UDP: "1 if it used UDP (fast, no delivery guarantee)",
  DHCP: "1 if a device was asking for a network address",
  ARP: "1 if a device was asking 'who has this address?' on the local network",
  ICMP: "1 if it was a ping or network error message",
  IPv: "1 if it used IP, the internet's addressing",
  LLC: "1 if it used LLC, a low-level link protocol",
  "Tot sum": "Total bytes of all packets in the batch",
  Min: "Smallest packet in the batch, in bytes",
  Max: "Biggest packet in the batch, in bytes",
  AVG: "Average packet size, in bytes",
  Std: "How much the packet sizes differ from each other",
  "Tot size": "Average packet length, in bytes",
  IAT: "Time since the previous packet (turned out to be a hidden clock, so it is not used: see step 2)",
  Number: "Number of packets in the batch",
  Magnitue: "Square root of (average incoming size + average outgoing size)",
  Radius: "Square root of how much incoming and outgoing sizes vary",
  Covariance: "How incoming and outgoing packet sizes move together",
  Variance: "Incoming size variation divided by outgoing size variation",
  Weight: "Incoming packets × outgoing packets",
}

/** The protocol columns: each is 1 when the batch used that protocol. */
export const PROTOCOLS = ["HTTP", "HTTPS", "DNS", "Telnet", "SMTP", "SSH", "IRC", "TCP", "UDP", "DHCP", "ARP", "ICMP"]
